package de.elmar_baumann.jbirthdays.ui;

import de.elmar_baumann.jbirthdays.ical.ExportToIcalAction;
import de.elmar_baumann.jbirthdays.imexport.QtBirthdaysDbImport;
import de.elmar_baumann.jbirthdays.util.Bundle;
import de.elmar_baumann.jbirthdays.util.Mnemonics;
import java.nio.charset.Charset;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * @author Elmar Baumann
 */
public class ToolsPanel extends javax.swing.JPanel {

    public static final String PROPERTY_IMPORTED = "imported";
    private static final long serialVersionUID = 1L;

    public ToolsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        Mnemonics.setMnemonics(this);
        Collection<Charset> charsets = Charset.availableCharsets().values();
        comboBoxImportCharsets.setModel(new DefaultComboBoxModel<>(charsets.toArray(new Charset[charsets.size()])));
        comboBoxImportCharsets.setSelectedItem(Charset.defaultCharset());
        setCharsetInfo();
    }

    private void setCharsetInfo() {
        String info = Bundle.getString(ToolsPanel.class, "ToolsPanel.Info.Charsets", "windows-1252", "UTF-8");
        labelCharsetsInfo.setText(info);
    }

    private void importQtDb() {
        int importCount = QtBirthdaysDbImport.importPersons(this, (Charset) comboBoxImportCharsets.getSelectedItem());
        if (importCount > 0) {
            firePropertyChange(PROPERTY_IMPORTED, false, true);
        }
        JOptionPane.showMessageDialog(this,
                Bundle.getString(ToolsPanel.class, "ToolsPanel.Imported", importCount),
                Bundle.getString(ToolsPanel.class, "ToolsPanel.Imported.Title"),
                JOptionPane.INFORMATION_MESSAGE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new javax.swing.JPanel();
        panelImport = new javax.swing.JPanel();
        panelOldQtBirthdayApp = new javax.swing.JPanel();
        buttonImportQtDb = new javax.swing.JButton();
        labelImportCharset = new javax.swing.JLabel();
        comboBoxImportCharsets = new javax.swing.JComboBox<>();
        labelCharsetsInfo = new javax.swing.JLabel();
        panelExport = new javax.swing.JPanel();
        buttonExportToIcal = new javax.swing.JButton();
        labelIcalInfo = new javax.swing.JLabel();
        panelFill = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelContent.setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/elmar_baumann/jbirthdays/ui/Bundle"); // NOI18N
        panelImport.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ToolsPanel.panelImport.border.title"))); // NOI18N
        panelImport.setLayout(new java.awt.GridBagLayout());

        panelOldQtBirthdayApp.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ToolsPanel.panelOldQtBirthdayApp.border.title"))); // NOI18N
        panelOldQtBirthdayApp.setLayout(new java.awt.GridBagLayout());

        buttonImportQtDb.setText(bundle.getString("ToolsPanel.buttonImportQtDb.text")); // NOI18N
        buttonImportQtDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportQtDbActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        panelOldQtBirthdayApp.add(buttonImportQtDb, gridBagConstraints);

        labelImportCharset.setText(bundle.getString("ToolsPanel.labelImportCharset.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        panelOldQtBirthdayApp.add(labelImportCharset, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        panelOldQtBirthdayApp.add(comboBoxImportCharsets, gridBagConstraints);

        labelCharsetsInfo.setText("Will be set programatically"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        panelOldQtBirthdayApp.add(labelCharsetsInfo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelImport.add(panelOldQtBirthdayApp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelContent.add(panelImport, gridBagConstraints);

        panelExport.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ToolsPanel.panelExport.border.title"))); // NOI18N
        panelExport.setLayout(new java.awt.GridBagLayout());

        buttonExportToIcal.setAction(new ExportToIcalAction(this));
        buttonExportToIcal.setText(bundle.getString("ToolsPanel.buttonExportToIcal.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelExport.add(buttonExportToIcal, gridBagConstraints);

        labelIcalInfo.setText(bundle.getString("ToolsPanel.labelIcalInfo.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelExport.add(labelIcalInfo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        panelContent.add(panelExport, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(panelContent, gridBagConstraints);

        javax.swing.GroupLayout panelFillLayout = new javax.swing.GroupLayout(panelFill);
        panelFill.setLayout(panelFillLayout);
        panelFillLayout.setHorizontalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFillLayout.setVerticalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(panelFill, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonImportQtDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportQtDbActionPerformed
        importQtDb();
    }//GEN-LAST:event_buttonImportQtDbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExportToIcal;
    private javax.swing.JButton buttonImportQtDb;
    private javax.swing.JComboBox<Charset> comboBoxImportCharsets;
    private javax.swing.JLabel labelCharsetsInfo;
    private javax.swing.JLabel labelIcalInfo;
    private javax.swing.JLabel labelImportCharset;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelExport;
    private javax.swing.JPanel panelFill;
    private javax.swing.JPanel panelImport;
    private javax.swing.JPanel panelOldQtBirthdayApp;
    // End of variables declaration//GEN-END:variables
}
