package de.elmar_baumann.jbirthdays.xmlrepo;

import de.elmar_baumann.jbirthdays.api.BirthdaysUtil;
import de.elmar_baumann.jbirthdays.util.Bundle;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Elmar Baumann
 */
class XmlFilePersonRepositorySettingsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    XmlFilePersonRepositorySettingsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        textFieldFile.setText(XmlFilePersonRepository.getFilename());
    }

    private void chooseDatabase() {
        JFileChooser fc = new JFileChooser(new File(XmlFilePersonRepository.getFilename()).getParent());
        fc.setMultiSelectionEnabled(false);
        fc.setDialogTitle(Bundle.getString(XmlFilePersonRepositorySettingsPanel.class, "XmlFilePersonRepositorySettingsPanel.ChooseDatabase.FileChosserTitle"));
        String filterDescription = Bundle.getString(XmlFilePersonRepositorySettingsPanel.class, "XmlFilePersonRepositorySettingsPanel.FileFilterDescription");
        FileNameExtensionFilter filter = new FileNameExtensionFilter(filterDescription, "xml");
        fc.setFileFilter(filter);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fc.getSelectedFile();
            XmlFilePersonRepository.INSTANCE.setFile(selectedFile);
            BirthdaysUtil.setPreferredRepositoryUuid(XmlFilePersonRepository.getUuid());
            textFieldFile.setText(selectedFile.getAbsolutePath());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new javax.swing.JPanel();
        labelFile = new javax.swing.JLabel();
        textFieldFile = new javax.swing.JTextField();
        buttonChooseDatabase = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        panelContent.setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/elmar_baumann/jbirthdays/xmlrepo/Bundle"); // NOI18N
        labelFile.setText(bundle.getString("XmlFilePersonRepositorySettingsPanel.labelFile.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelContent.add(labelFile, gridBagConstraints);

        textFieldFile.setEditable(false);
        textFieldFile.setColumns(40);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelContent.add(textFieldFile, gridBagConstraints);

        buttonChooseDatabase.setText(bundle.getString("XmlFilePersonRepositorySettingsPanel.buttonChooseDatabase.text")); // NOI18N
        buttonChooseDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseDatabaseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelContent.add(buttonChooseDatabase, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(panelContent, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonChooseDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseDatabaseActionPerformed
        chooseDatabase();
    }//GEN-LAST:event_buttonChooseDatabaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseDatabase;
    private javax.swing.JLabel labelFile;
    private javax.swing.JPanel panelContent;
    private javax.swing.JTextField textFieldFile;
    // End of variables declaration//GEN-END:variables

}
